### ISSUE TITLE
Application for GoRust org

### ISSUE THREAD

**Issue by angusguo** [go-rust/community#3]
## 前提要求
要加入GoRust，你需要掌握Go或者Reactjs其中一种，如果两个都会，恭喜你，你离核心成员已经不远了

## 编程技能(Your programming skills)
请详细介绍你的前后端开发技能，Go和Reactjs必须要会一种
- 会一点go，目前仍在学习中。
- python也会一点，嗯也在学习中。
- 会写一点vue。

## 是否有意向成为全栈
GoRust极其希望开发人员能成为全栈，这样彼此之间的协作能力和沟通效率能大幅上升
- Absolutely
- 希望能跟着社群的大佬学习到新的东西，提升自己！

**Comment by sunface** [comment]
application passed
